; Copyright (C) Yagnesh Raghava Yakkala. http://yagnesh.org
;    File: primitive.ncl
; Created: Thursday, January 19 2012
; License: GPL v3 or later. <http://www.gnu.org/licenses/gpl.html>
;
; Description:
; load general universal settings that are never need to change in the
; code. May be some helper functions which have nothing to do with the
; output

load "$VISWRF/lib/helpers.ncl"

;;; primitive.ncl ends here
